### ISSUE TITLE
[Bug]: Won't exit snack explorer picker properly after rename attempt with `dressing.nvim`,  `snacks.input.nvim`

### ISSUE THREAD

**Issue by woertsposzibllen4me** [mrjones2014/smart-splits.nvim#342]
### Similar Issues

- [x] Before filing, I have searched for similar issues.

### Neovim Version

NVIM v0.12.0-dev-197+g1dbede5b93
Build type: RelWithDebInfo
LuaJIT 2.1.1744317938

### Multiplexer Integration

tmux

### Multiplexer Version

This is an interal nvim thing.

### Steps to Reproduce

1. press `<space>e` to open explorer
2. press `r` to rename some file
3. press `esc` twice to espace `dressing.nvim` renaming buffer
4. press `C-l` to try to access main eiditing window

### Expected Behavior

Cursor moves from explorer picker to main window.

### Actual Behavior

Cursor will not move.

this can be fixed with:
```lua
      {
        "<C-l>",
        function()
          if vim.bo.filetype == "snacks_picker_list" then
            local win_config = vim.api.nvim_win_get_config(0)
            if win_config.zindex == 33 then -- Snack explorer is on same zindex as main window
              vim.cmd("wincmd l")
            end
          else
            require("smart-splits").move_cursor_right()
          end
        end,
        desc = "Move to right split",
      },
```

### Minimal Configuration to Reproduce

```lua
-- usage "nvim -u this_filename.lua"
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()
vim.g.mapleader = " " -- Set leader key to space

--- @ diagnostic disable: missing-fields
require("lazy.minit").repro({
  spec = {
    {
      "folke/snacks.nvim",
      lazy = false,
      keys = {
        {
          "<leader>e",
          function()
            require("snacks").explorer()
          end,
        },
      },
    },
    {
      "stevearc/dressing.nvim",
      opts = {},
    },
    {
      "mrjones2014/smart-splits.nvim",
      lazy = false,
      opts = {
        at_edge = "stop",
      },
      keys = {
        {
          "<C-h>",
          function()
            require("smart-splits").move_cursor_left()
          end,
          desc = "Move to left split",
        },
        {
          "<C-j>",
          function()
            require("smart-splits").move_cursor_down()
          end,
          desc = "Move to bottom split",
        },
        {
          "<C-k>",
          function()
            require("smart-splits").move_cursor_up()
          end,
          desc = "Move to top split",
        },
        {
          "<C-l>",
          function()
            require("smart-splits").move_cursor_right()
          end,
          desc = "Move to right split",
        },
      },
    },
  },
})
```

### Additional Details and/or Screenshots

I'm not sure you want to cover this case since it involves 2 others plugins but just reporting in case you'd want to. Something happens when the [dressing](https://github.com/stevearc/dressing.nvim) buffer gets created that makes this plugin not recognize that we are in nvim anymore.

EDIT : This happens with [snacks.input](https://github.com/folke/snacks.nvim/blob/main/docs/input.md) too

**Comment by mrjones2014** [comment]
If we do that then we can update `utils.is_floating_window()` to exclude `Snacks.explorer()` window so that `smart-splits.nvim` treats it like a non-floating window.

**Comment by mrjones2014** [comment]
> the issue of the buffers created from dressing and snacks.input being the actual obstruction to this plugin's logic.

yep exactly.

Until such time that we can reliably detect these edge cases, I lean towards the solution being "just add docs".

**Comment by romanorac** [comment]
I use latest lazyvim in wezterm with smartsplits. I have an issue when I enter the snacks explorer, which is on the left, and then go to the right, it should go to my code editor, but it jumps to the wezterm pane, which is further on the right.

Is there any known solution for this?

**Comment by mrjones2014** [comment]
That happens when you have `float_win_behavior = 'mux'` because the snacks explorer window is technically a floating window.

Unfortunately there is not a great way to add special handling for it because it's also just a snacks picker in disguise, so the filetype is `snacks_picker_list` which is the same as normal pickers, which we _do_ want to treat like normal picker windows.


However looking again, I think I missed some context in the original message. I would be okay with checking `zindex == 33` _in combination with_ the filetype being `snacks_picker_list`.

I'll put up a PR for yall to test.

**Comment by mrjones2014** [comment]
Please test #342

**Comment by romanorac** [comment]
Thanks for a quick fix. The issue that I described above is solved:

```
return {
  "mrjones2014/smart-splits.nvim",
  commit = "c4afaf23141651845e6e1966d936d79ff8939e4d",
}
```

**Comment by Torsteinws** [comment]
I found another issue that seems related.

It seems like smart-splits.nvim is not able to detect that it is on an edge when the keyboard focus is inside the snacks explorer.

For example, here it is not possible to navigate to the left pane when the snacks explorer is open:

https://github.com/user-attachments/assets/2586e2ef-a6e6-4771-aeca-4798004eab4e

And here you cannot navigate to the bottom pane if your keyboard focus is inside the snacks explorer:

https://github.com/user-attachments/assets/b541899a-151a-4d41-9f09-42e5a8e77d76


It's not really a big issue, but interesting to keep in mind when looking for a way to handle that misbehaving snacks explorer.

**Comment by Torsteinws** [comment]
Good news! The resize bug resolved itself after I updated all my plugins. I am currently using smart-splits.nvim pre #380, and everything works perfect now as far as I can tell.

Maybe you can consider to revert #380?

**Comment by mrjones2014** [comment]
Oh interesting! Could you narrow down the specific commit which fixes the issue? If I could better understand _why_ its fixed, I'd definitely consider reverting #381!

**Comment by pwnalone** [comment]
I am also not seeing the resize issue anymore when pinning the plugin at #380, but the second bug that Torsteinws [pointed out](https://github.com/mrjones2014/smart-splits.nvim/issues/342#issuecomment-3444220929) is still present.

@mrjones2014 It appears that commit [913379c](https://github.com/folke/snacks.nvim/commit/913379ccd2679fc11462479205897e584496c855) in `snacks.nvim` is what resolved the resize issue. Here's a minimal config that may help troubleshoot things further.

```lua
-- vi: ts=2 sw=2 et

vim.env.LAZY_STDPATH = ".repro"

load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    {
      "mrjones2014/smart-splits.nvim",
      commit = "c4afaf23141651845e6e1966d936d79ff8939e4d",
    },
    {
      "folke/snacks.nvim",
      commit = "913379ccd2679fc11462479205897e584496c855",  -- Append '^' to see the resize bug again.
      opts = { explorer = { enabled = true } },
      keys = {
        {
          "ge",
          function()
            Snacks.explorer()
          end,
          desc = "File Explorer",
        },
      },
    },
  },
})

-- Switch windows.
vim.keymap.set({ "n", "i", "t" }, "<M-h>", function()
  require("smart-splits").move_cursor_left()
end, { desc = "Go to Left Window" })
vim.keymap.set({ "n", "i", "t" }, "<M-j>", function()
  require("smart-splits").move_cursor_down()
end, { desc = "Go to Lower Window" })
vim.keymap.set({ "n", "i", "t" }, "<M-k>", function()
  require("smart-splits").move_cursor_up()
end, { desc = "Go to Upper Window" })
vim.keymap.set({ "n", "i", "t" }, "<M-l>", function()
  require("smart-splits").move_cursor_right()
end, { desc = "Go to Right Window" })
vim.keymap.set({ "n", "i", "t" }, "<M-;>", function()
  require("smart-splits").move_cursor_previous()
end, { desc = "Go to Previous Window" })

-- Resize windows.
vim.keymap.set({ "n", "i", "t" }, "<M-H>", function()
  require("smart-splits").resize_left()
end, { desc = "Resize Window Leftwards" })
vim.keymap.set({ "n", "i", "t" }, "<M-J>", function()
  require("smart-splits").resize_down()
end, { desc = "Resize Window Upwards" })
vim.keymap.set({ "n", "i", "t" }, "<M-K>", function()
  require("smart-splits").resize_up()
end, { desc = "Resize Window Downwards" })
vim.keymap.set({ "n", "i", "t" }, "<M-L>", function()
  require("smart-splits").resize_right()
end, { desc = "Resize Window Rightwards" })
```

**Comment by mrjones2014** [comment]
> the second bug that Torsteinws https://github.com/mrjones2014/smart-splits.nvim/issues/342#issuecomment-3444220929 is still present.

Yeah, this is another weird case of "technically not a bug" because of how Snacks.explorer is weirdly using a floating window -- technically this plugin considers floating windows to never be at an edge.

However, since Snacks.explorer seems to _always_ be at an edge (correct me if I am wrong), then I think we're safe now to treat the snacks explorer specially in the following ways:

- Pretend it is not floating
- Always assume it is at an edge

Let me know if anyone would like to PR this, otherwise I will probably not get to it for a bit with holidays and all coming up.
